In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Nimish\Desktop\Customer_Churn_Prediction\data\WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [5]:
# shape task
df.shape

(7043, 21)

In [7]:
df.shape[0]  # for number of rows
df.shape[1]  # for number of columns

21

In [8]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [10]:
list(df)

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [11]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [14]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [27]:
df['TotalCharges'].dtype

dtype('O')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
df['Churn'].nunique()

2

In [41]:
# How many customers stayed and how many customers left
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [42]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [44]:
df.describe(include="object")

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [46]:
df['InternetService'].unique().tolist()

['DSL', 'Fiber optic', 'No']

In [47]:
df['Contract'].unique().tolist()

['Month-to-month', 'One year', 'Two year']

In [48]:
# Task 6
df["TotalCharges"].head(20)

0       29.85
1      1889.5
2      108.15
3     1840.75
4      151.65
5       820.5
6      1949.4
7       301.9
8     3046.05
9     3487.95
10     587.45
11      326.8
12     5681.1
13     5036.3
14    2686.05
15    7895.15
16    1022.95
17    7382.25
18     528.35
19     1862.9
Name: TotalCharges, dtype: object

In [53]:
df['tenure'].unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39])

In [54]:
df['tenure'].value_counts()

tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

In [63]:
df['gender'].unique().tolist()

['Female', 'Male']

In [ ]:
df['Partner'].unique().tolist()

['Yes', 'No']

In [65]:
df['Dependents'].unique().tolist()

['No', 'Yes']

In [66]:
df['Contract'].unique().tolist()

['Month-to-month', 'One year', 'Two year']

In [67]:
df['PaymentMethod'].unique().tolist()

['Electronic check',
 'Mailed check',
 'Bank transfer (automatic)',
 'Credit card (automatic)']

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [75]:
df['MonthlyCharges'].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [76]:
df['tenure'].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [81]:
df["TotalCharges"].unique().tolist()

['29.85',
 '1889.5',
 '108.15',
 '1840.75',
 '151.65',
 '820.5',
 '1949.4',
 '301.9',
 '3046.05',
 '3487.95',
 '587.45',
 '326.8',
 '5681.1',
 '5036.3',
 '2686.05',
 '7895.15',
 '1022.95',
 '7382.25',
 '528.35',
 '1862.9',
 '39.65',
 '202.25',
 '20.15',
 '3505.1',
 '2970.3',
 '1530.6',
 '4749.15',
 '30.2',
 '6369.45',
 '1093.1',
 '6766.95',
 '181.65',
 '1874.45',
 '20.2',
 '45.25',
 '7251.7',
 '316.9',
 '3548.3',
 '3549.25',
 '1105.4',
 '475.7',
 '4872.35',
 '418.25',
 '4861.45',
 '981.45',
 '3906.7',
 '97',
 '144.15',
 '4217.8',
 '4254.1',
 '3838.75',
 '1426.4',
 '1752.65',
 '633.3',
 '4456.35',
 '1752.55',
 '6311.2',
 '7076.35',
 '894.3',
 '7853.7',
 '4707.1',
 '5450.7',
 '2962',
 '957.1',
 '857.25',
 '244.1',
 '3650.35',
 '2497.2',
 '930.9',
 '887.35',
 '49.05',
 '1090.65',
 '7099',
 '1424.6',
 '177.4',
 '6139.5',
 '2688.85',
 '482.25',
 '2111.3',
 '1216.6',
 '79.35',
 '565.35',
 '496.9',
 '4327.5',
 '973.35',
 '918.75',
 '2215.45',
 '1057',
 '927.1',
 '1009.25',
 '2570.2',
 '74.7',
 '5714.25',
 '7107',
 '7459.05',
 '927.35',
 '4748.7',
 '113.85',
 '1107.2',
 '2514.5',
 '19.45',
 '3605.6',
 '3027.25',
 '7611.85',
 '100.2',
 '7303.05',
 '927.65',
 '3921.3',
 '1363.25',
 '5238.9',
 '3042.25',
 '3954.1',
 '2868.15',
 '3423.5',
 '248.4',
 '1126.35',
 '1064.65',
 '835.15',
 '2151.6',
 '5515.45',
 '112.75',
 '229.55',
 '350.35',
 '62.9',
 '3027.65',
 '2135.5',
 '1723.95',
 '19.75',
 '3985.35',
 '1215.65',
 '1502.65',
 '3260.1',
 '35.45',
 '81.25',
 '1188.2',
 '1778.5',
 '1277.75',
 '1170.55',
 '70.45',
 '6425.65',
 '563.65',
 '5971.25',
 '5289.05',
 '1756.2',
 '6416.7',
 '61.35',
 '45.65',
 '1929.95',
 '1071.4',
 '564.35',
 '655.5',
 '7930.55',
 '5215.25',
 '113.5',
 '1152.8',
 '1821.95',
 '419.9',
 '1024',
 '251.6',
 '764.55',
 '1592.35',
 '135.2',
 '3958.25',
 '233.9',
 '1363.45',
 '273',
 '6254.45',
 '2651.2',
 '321.4',
 '3539.25',
 '242.8',
 '1181.75',
 '5000.2',
 '654.55',
 '780.2',
 '1145.7',
 '503.6',
 '1559.25',
 '1252',
 '29.95',
 '45.3',
 '662.65',
 '2453.3',
 '1111.65',
 '24.8',
 '1023.85',
 '82.15',
 '244.8',
 '2379.1',
 '3173.35',
 '531',
 '1375.4',
 '8129.3',
 '1192.7',
 '1901.65',
 '587.4',
 '6519.75',
 '8041.65',
 '20.75',
 '2681.15',
 '1112.3',
 '7405.5',
 '1033.95',
 '2958.95',
 '2684.85',
 '4179.2',
 '79.9',
 '1934.45',
 '6654.1',
 '84.5',
 '25.25',
 '1124.2',
 '540.05',
 '1975.85',
 '3437.45',
 '3139.8',
 '3789.2',
 '5324.5',
 '624.6',
 '268.35',
 '1836.9',
 '179.35',
 '219.35',
 '1288.75',
 '2545.75',
 '55.2',
 '2723.15',
 '4107.25',
 '5760.65',
 '4747.5',
 '84.6',
 '1566.9',
 '702',
 '114.1',
 '299.05',
 '1305.95',
 '1120.3',
 '284.35',
 '6350.5',
 '7878.3',
 '3187.65',
 '6126.15',
 '731.3',
 '273.4',
 '2531.8',
 '1074.3',
 '48.55',
 '4298.45',
 '4619.55',
 '147.15',
 '40.2',
 '2633.3',
 '193.05',
 '4103.9',
 '7008.15',
 '5791.1',
 '80.55',
 '1228.65',
 '132.2',
 '1364.3',
 '4925.35',
 '1520.1',
 '5032.25',
 '5526.75',
 '1195.25',
 '2007.25',
 '1099.6',
 '1732.95',
 '1511.2',
 '3450.15',
 '2172.05',
 '70.6',
 '401.1',
 '5624.85',
 '1339.8',
 '771.95',
 '244.75',
 '322.9',
 '498.25',
 '25.4',
 '3687.75',
 '1779.95',
 '1783.6',
 '927.15',
 '70',
 '606.55',
 '435.4',
 '1712.7',
 '2021.2',
 '1940.8',
 '567.8',
 '220.35',
 '20.25',
 '5436.45',
 '3437.5',
 '3015.75',
 '73.6',
 '1509.8',
 '396.1',
 '356.65',
 '4109',
 '3141.7',
 '1229.1',
 '2303.35',
 '2054.4',
 '3741.85',
 '3682.45',
 '19.25',
 '1886.25',
 '4895.1',
 '341.6',
 '415.55',
 '5686.4',
 '1355.1',
 '3058.65',
 '2231.05',
 '3236.35',
 '4350.1',
 '4264',
 '44.8',
 '422.3',
 '4176.7',
 '5138.1',
 '880.05',
 '139.05',
 '973.65',
 '1470.05',
 '739.35',
 '161.95',
 '4422.95',
 '511.25',
 '155.8',
 '5293.95',
 '4759.85',
 '6148.45',
 '3565.65',
 '6603',
 '1830.1',
 '6223.8',
 '4508.65',
 '1328.15',
 '865',
 '72.1',
 '168.2',
 '1303.5',
 '996.85',
 '6430.9',
 '2278.75',
 '681.4',
 '574.35',
 '371.9',
 '840.1',
 '846',
 '889',
 '6823.4',
 '805.1',
 '4016.75',
 '83.75',
 '3959.15',
 '2878.55',
 '945.7',
 '1373.05',
 '492.55',
 '1406',
 '19.15',
 '6962.85',
 '8126.65',
 '690.25',
 '181.5',
 '830.8',
 '5608.4',
 '3646.8',
 '3662.25',
 '25.35',
 '2566.5',
 '5308.7',
 '1410.25',
 '3339.05',
 '50.65',
 '4732.35',
 '90.85',
 '5067.45',
 '214.75',
 '4874.7',
 '2348.45',
 '4063',
 '44',
 '2595.25',
 '2309.55',
 '89.3',
 '367.55',
 '3944.5',
 '5965.95',
 '3694.7',
 '2524.45',
 '1803.7',
 '415.1',
 '624.15',
 '237.7',
 '7007.6',
 '3848.8',
 '419.4',
 '1468.75',
 '5812',
 '2861.45',
 '19.9',
 '19.6',
 '233.7',
 '1066.15',
 '2149.05',
 '4473',
 '3545.05',
 '1195.75',
 '6858.9',
 '1024.7',
 '1845.9',
 '75.3',
 '132.25',
 '515.45',
 '2830.45',
 '1110.5',
 '449.3',
 '2838.55',
 '5376.4',
 '858.6',
 '1395.05',
 '3975.7',
 '1182.55',
 '4784.45',
 '119.5',
 '518.9',
 '899.45',
 '1183.8',
 '720.05',
 '8468.2',
 '3161.2',
 '55.05',
 '1882.55',
 '5070.4',
 '6049.5',
 '1166.7',
 '2937.65',
 '6396.45',
 '69.55',
 '1270.25',
 '759.55',
 '7611.55',
 '1642.75',
 '1545.4',
 '3582.4',
 '2227.1',
 '1417.9',
 '2494.65',
 '2768.35',
 '2369.3',
 '38',
 '75.1',
 '100.9',
 '1614.05',
 '385.9',
 '673.25',
 '8404.9',
 '2799.75',
 '6538.45',
 '6588.95',
 '868.1',
 '734.35',
 '330.6',
 '55',
 '564.4',
 '1315.35',
 '1861.5',
 '2747.2',
 '554.05',
 '453.4',
 '994.8',
 '225.75',
 '2145',
 '1671.6',
 '8003.8',
 '680.05',
 '6130.85',
 '1415',
 '6201.95',
 ' ',
 '74.35',
 '6597.25',
 '114.15',
 '139.4',
 '3902.6',
 '20.4',
 '903.6',
 '1785.65',
 '1397.65',
 '131.05',
 '1238.45',
 '3899.05',
 '5676',
 '4543.15',
 '4326.8',
 '5502.55',
 '1782.4',
 '851.8',
 '167.5',
 '502.85',
 '19.85',
 '1818.3',
 '6300.15',
 '334.8',
 '5916.95',
 '2852.4',
 '4131.95',
 '1546.3',
 '302.6',
 '1929.35',
 '265.45',
 '6989.45',
 '1442',
 '4713.4',
 '1758.6',
 '3480',
 '4738.3',
 '8399.15',
 '5430.35',
 '686.95',
 '5706.3',
 '490.65',
 '1360.25',
 '174.45',
 '7379.8',
 '85',
 '1021.75',
 '5029.05',
 '1955.4',
 '6744.2',
 '4946.7',
 '8248.5',
 '601.6',
 '19.55',
 '834.1',
 '597',
 '2647.2',
 '3266',
 '6744.25',
 '5265.5',
 '311.6',
 '7966.9',
 '8220.4',
 '1153.25',
 '514.75',
 '2596.15',
 '3808',
 '2708.2',
 '760.05',
 '49.3',
 '6033.3',
 '89.05',
 '516.15',
 '5861.75',
 '445.95',
 '4973.4',
 '1667.25',
 '5357.75',
 '3527.6',
 '422.6',
 '1103.25',
 '2754',
 '697.25',
 '5614.45',
 '3204.4',
 '4747.65',
 '3082.1',
 '597.9',
 '3365.4',
 '38.8',
 '233.55',
 '346.2',
 '19',
 '61.7',
 '85.7',
 '3342.45',
 '85.1',
 '7422.1',
 '6668.05',
 '8071.05',
 '1174.8',
 '5435',
 '2438.6',
 '45.6',
 '713.75',
 '916.15',
 '237.2',
 '4614.55',
 '1414.45',
 '1170.5',
 '47.7',
 '4859.25',
 '4903.2',
 '3608',
 '6094.25',
 '3084.9',
 '2356.75',
 '8306.05',
 '6786.4',
 '248.95',
 '663.05',
 '1357.1',
 '4860.35',
 '3418.2',
 '631.4',
 '186.3',
 '6976.75',
 '4884.85',
 '522.95',
 '362.6',
 '5755.8',
 '3355.65',
 '406.95',
 '137.6',
 '2395.7',
 '1968.1',
 '6819.45',
 '7943.45',
 '4547.25',
 '4687.9',
 '2473.95',
 '6562.9',
 '176.3',
 '2236.2',
 '6985.65',
 '3109.9',
 '4911.35',
 '5794.65',
 '855.3',
 '1620.2',
 '2499.3',
 '89.55',
 '4287.2',
 '394.85',
 '1899.65',
 '45.7',
 '3442.15',
 '161.5',
 '1732.6',
 '222.3',
 '74.6',
 '655.3',
 '475.25',
 '164.3',
 '865.1',
 '6132.7',
 '3597.5',
 '35.9',
 '697.65',
 '96.05',
 '428.7',
 '20.05',
 '4459.15',
 '1167.6',
 '238.1',
 '145.15',
 '1453.1',
 '191.05',
 '4039.3',
 '1039.45',
 '1336.1',
 '75.05',
 '493.4',
 '2550.9',
 '7246.15',
 '1203.95',
 '62.25',
 '313.6',
 '3775.85',
 '80',
 '4616.05',
 '195.65',
 '4188.4',
 '71.1',
 '49.9',
 '1266.4',
 '91.1',
 '1623.4',
 '4149.45',
 '20.45',
 '2344.5',
 '1013.05',
 '270.7',
 '417',
 '20.65',
 '6316.2',
 '168.15',
 '4018.05',
 '4811.6',
 '4189.7',
 '2848.45',
 '2516.2',
 '33.6',
 '208.45',
 '2015.35',
 '3739.8',
 '2964',
 '2263.4',
 '2211.8',
 '1683.7',
 '1519',
 '1164.05',
 '1710.9',
 '4245.55',
 '4145.9',
 '2664.3',
 '1277.5',
 '5589.3',
 '34.75',
 '381.3',
 '141.5',
 '3105.55',
 '204.55',
 '605.9',
 '356.1',
 '2758.15',
 '4805.65',
 '3941.7',
 '92.75',
 '1901.05',
 '5730.7',
 '2423.4',
 '1653.45',
 '3327.05',
 '7085.5',
 '3344.1',
 '6697.35',
 '2879.9',
 '137.1',
 '1008.55',
 '1551.6',
 '202.15',
 '7882.25',
 '8196.4',
 '202.9',
 '855.1',
 '5817',
 '1652.95',
 '5600.15',
 '515.75',
 '190.5',
 '1842.8',
 '1253.8',
 '57.2',
 '1269.55',
 '6563.4',
 '20.8',
 '1907.85',
 '208.85',
 '4758.8',
 '1292.6',
 '363.15',
 '1600.25',
 '275.7',
 '3089.1',
 '1175.6',
 '237.3',
 '1444.65',
 '454.15',
 '3036.75',
 '8065.65',
 '92.5',
 '184.65',
 '6152.3',
 '89.5',
 '5154.5',
 '220.45',
 '1510.3',
 '52.2',
 '2588.95',
 '4874.8',
 '3983.6',
 '2003.6',
 '1832.4',
 '4908.25',
 '3590.2',
 '5023',
 '146.6',
 '2339.3',
 '298.7',
 '143.65',
 '2548.65',
 '507.4',
 '20',
 '6125.4',
 '5411.4',
 '1058.25',
 '903.8',
 '3009.5',
 '489.45',
 '5468.45',
 '1058.1',
 '7616',
 '4113.1',
 '6017.65',
 '7250.15',
 '1108.2',
 '938.65',
 '94.15',
 '2088.05',
 '178.7',
 '5656.75',
 '2317.1',
 '5986.45',
 '6751.35',
 '3566.6',
 '4889.3',
 '318.1',
 '1563.95',
 '1430.25',
 '644.35',
 '372.45',
 '5453.4',
 '1442.6',
 '5610.7',
 '963.95',
 '5222.3',
 '3340.55',
 '292.8',
 '5774.55',
 '4487.3',
 '44.4',
 '2854.95',
 '905.55',
 '5509.3',
 '7589.8',
 '229.6',
 '394.1',
 '89.9',
 '295.95',
 '5459.2',
 '444.75',
 '6782.15',
 '6510.45',
 '8476.5',
 '4461.85',
 '62',
 '352.65',
 '1424.9',
 '6413.65',
 '6309.65',
 '50.8',
 '5898.6',
 '4719.75',
 '457.3',
 '5822.3',
 '1463.5',
 '307.4',
 '2104.55',
 '319.15',
 '2337.45',
 '104.3',
 '5084.65',
 '121.25',
 '7015.9',
 '5598',
 '1269.1',
 '3027.4',
 '4634.35',
 '113.95',
 '1582.75',
 '3077',
 '4039.5',
 '1665.2',
 '1043.3',
 '504.2',
 '497.55',
 '7511.65',
 '1782',
 '609.65',
 '2857.6',
 '3247.55',
 '6215.35',
 '2823',
 '5017.9',
 '2619.25',
 '24.6',
 '4965.1',
 '2679.7',
 '8310.55',
 '5682.25',
 '1120.95',
 '4914.9',
 '27.55',
 '923.5',
 '1625.65',
 '6068.65',
 '5398.6',
 '918.6',
 '234.85',
 '1231.85',
 '170.9',
 '7984.15',
 '688.65',
 '1288.3',
 '7848.5',
 '267',
 '1798.9',
 '73.55',
 '1643.55',
 '4807.45',
 '2193',
 '2239.4',
 '1505.9',
 '255.35',
 '1189.4',
 '4786.15',
 '1820.9',
 '2404.15',
 '205.05',
 '952.3',
 '7039.45',
 '2538.05',
 '1212.85',
 '2651.1',
 '1304.8',
 '360.1',
 '435.45',
 '308.05',
 '434.5',
 '7118.9',
 '320.45',
 '531.55',
 '382.2',
 '2001',
 '4919.7',
 '5645.8',
 '215.8',
 '77.6',
 '2896.55',
 '3395.8',
 '759.35',
 '85.15',
 '535.55',
 '1253.15',
 '955.15',
 '2162.6',
 '44.7',
 '1813.35',
 '245.15',
 '2028.8',
 '2723.75',
 '365.8',
 '551.95',
 '4054.2',
 '832.35',
 '112.3',
 '60.65',
 '5550.1',
 '174.8',
 '90.55',
 '4733.1',
 '4048.95',
 '1359.7',
 '4542.35',
 '7532.15',
 '69.9',
 '888.65',
 '6383.35',
 '1916',
 '413',
 '808.95',
 '1886.4',
 '86.6',
 '1679.25',
 '2656.5',
 '540.95',
 '537.35',
 '678.8',
 '4513.65',
 '1423.85',
 '555.4',
 '225.55',
 '268.45',
 '2917.5',
 '2416.1',
 '424.45',
 '1492.1',
 '132.4',
 '660.9',
 '1893.95',
 '284.9',
 '784.25',
 '417.7',
 '5016.25',
 '1612.75',
 '119.75',
 '3204.65',
 '485.2',
 '160.85',
 '4145.25',
 '827.45',
 '49.5',
 '990.85',
 '696.35',
 ...]